function getForm() {
    
    var form = {
        ICType : 'Panel',
        ICElementNum : '0',
        ICStateNum : '3',
        ICAction : 'CLASS_SRCH_WRK2_STRM$45$',
        ICXPos : '0',
        ICYPos : '0',
        ICFocus : '',
        ICSaveWarningFilter : '0',
        ICChanged : '-1',
        ICResubmit : '0',
        ICSID : 'LbW7ZLkhXs9G',
        ICModalWidget : '0',
        ICZoomGrid : '0',
        ICZoomGridRt : '0',
        ICModalLongClosed : '',
        ICActionPrompt : 'false',
        ICFind : '',
        ICAddCount : '',
        CLASS_SRCH_WRK2_INSTITUTION$42$ : '',
        CLASS_SRCH_WRK2_STRM$45$ : '',
        SSR_CLSRCH_WRK_SUBJECT_SRCH$0 : '',
        SSR_CLSRCH_WRK_SSR_EXACT_MATCH1$1 : 'G',
        SSR_CLSRCH_WRK_CATALOG_NBR$1 : '0',
        SSR_CLSRCH_WRK_ACAD_CAREER$2 : '',
        SSR_CLSRCH_WRK_CRSE_ATTR$3 : '',
        SSR_CLSRCH_WRK_CRSE_ATTR_VALUE$3 : '',
        SSR_CLSRCH_WRK_CU_RQMNT_DESIGNTN$4 : '',
        SSR_CLSRCH_WRK_SSR_OPEN_ONLY$chk$5 : 'Y',
        SSR_CLSRCH_WRK_SSR_OPEN_ONLY$5 : 'Y',
        SSR_CLSRCH_WRK_SESSION_CODE$6 : '',
        SSR_CLSRCH_WRK_INSTRUCTION_MODE$7 : '',
        SSR_CLSRCH_WRK_SSR_START_TIME_OPR$8 : 'GE',
        SSR_CLSRCH_WRK_MEETING_TIME_START$8 : '',
        SSR_CLSRCH_WRK_SSR_END_TIME_OPR$8 : 'LE',
        SSR_CLSRCH_WRK_MEETING_TIME_END$8 : '',
        SSR_CLSRCH_WRK_INCLUDE_CLASS_DAYS$9 : 'I',
        SSR_CLSRCH_WRK_MON$chk$9 : '',
        SSR_CLSRCH_WRK_TUES$chk$9 : '',
        SSR_CLSRCH_WRK_WED$chk$9 : '',
        SSR_CLSRCH_WRK_THURS$chk$9 : '',
        SSR_CLSRCH_WRK_FRI$chk$9 : '',
        SSR_CLSRCH_WRK_SAT$chk$9 : '',
        SSR_CLSRCH_WRK_SUN$chk$9 : '',
        SSR_CLSRCH_WRK_CLASS_NBR$10 : '',
        SSR_CLSRCH_WRK_DESCR$11 : '',
        SSR_CLSRCH_WRK_SSR_UNITS_MIN_OPR$12 : 'GE',
        SSR_CLSRCH_WRK_UNITS_MINIMUM$12 : '',
        SSR_CLSRCH_WRK_SSR_UNITS_MAX_OPR$12 : 'LE',
        SSR_CLSRCH_WRK_UNITS_MAXIMUM$12 : '',
        SSR_CLSRCH_WRK_SSR_COMPONENT$13 : '',
        SSR_CLSRCH_WRK_CAMPUS$14 : '',
        SSR_CLSRCH_WRK_LOCATION$15 : '',
        SSR_CLSRCH_WRK_SSR_EXACT_MATCH2$16 : 'B',
        SSR_CLSRCH_WRK_LAST_NAME$16 : ''
    };

    return form;
}

module.exports = {
    getForm: getForm
}